log:
  level: WARNING
accessLog: {}
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
#   kubessl:
#     address: ':443/tcp'

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic

tracing:
  jaeger:
    localAgentHostPort: '127.0.0.1:6831'
    propagation: b3
