# tcp:
#   services:
#     kube-ssl-service:
#       loadBalancer:
#         servers:
#         - address: '192.168.88.34:9001'
#   routers:
#     kube-ssl:
#       rule: "HostSNI(`registry.kube.zz`)"
#       entryPoints:
#       - kubessl
#       service: kube-ssl-service

http:
  services:
    kube:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.88.34:9000/"

  routers:
    api:
      entryPoints:
        - web
      rule: 'Host(`localhost`)'
      service: api@internal

    kube:
      entryPoints:
        - web
      rule: 'HostRegexp(`{sub}.kube.zz`) || HostRegexp(`{sub}.{sub2}.kube.zz`)'
      service: kube

    metrics:
      entryPoints:
        - web
      rule: "Host(`metrics.zz`) && Path(`/metrics`)"
      service: prometheus@internal
      middlewares:
        - metricAuth

  middlewares:
    metricAuth:
      basicAuth:
        users:
          - someuser:$apr1$Et9ea2ot$7o1vxitB.yb3es1bz3zWu.
