http:
  services:
    kube:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "http://192.168.88.34:9000/"

  routers:
    kube:
      rule: "Host(`traefik.kube.zz`)"
      service: kube

tcp:
  services:
    kube-ssl-service:
      loadBalancer:
        servers:
          - address: '192.168.88.34:9001'
  routers:
    kube-ssl:
      entryPoints:
        - kubessl
      service: kube-ssl-service
